using System;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MauiApp1.Models;
using MauiApp1.Services;

namespace MauiApp1.ViewModels {
    public partial class NewAccessRequestViewModel : ObservableObject {
        private readonly IAccessRequestService _requests;
        private readonly IBusinessSystemService _systems;
        private readonly ICurrentUserService _currentUser;

        public NewAccessRequestViewModel(
            IAccessRequestService requests,
            IBusinessSystemService systems,
            ICurrentUserService currentUser) {
            _requests = requests;
            _systems = systems;
            _currentUser = currentUser;
        }

        // ---- Picker sources ----
        public ObservableCollection<BusinessSystem> Systems { get; } = new();
        public ObservableCollection<string> AvailableRoles { get; } = new();

        // ---- Selections ----
        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(SubmitCommand))]
        private BusinessSystem? _selectedSystem;

        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(SubmitCommand))]
        private string? _selectedRole;

        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(SubmitCommand))]
        private string _justification = string.Empty;

        // ---- State ----
        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(SubmitCommand))]
        private bool _isBusy;

        [ObservableProperty] private bool _isLoading;
        [ObservableProperty] private bool _hasSystems;
        [ObservableProperty] private bool _noSystemsAvailable;
        [ObservableProperty] private string? _errorMessage;

        // When SelectedSystem changes, refresh the roles dropdown.
        // partial generated by CommunityToolkit.Mvvm — we just supply the body.
        partial void OnSelectedSystemChanged(BusinessSystem? value) {
            AvailableRoles.Clear();
            SelectedRole = null;

            if (value?.AvailableRoles is not null) {
                foreach (var r in value.AvailableRoles) {
                    AvailableRoles.Add(r);
                }
            }
        }

        public async Task LoadSystemsAsync() {
            IsLoading = true;
            ErrorMessage = null;
            try {
                var data = await _systems.GetActiveAsync();
                Systems.Clear();
                foreach (var s in data) Systems.Add(s);

                HasSystems = Systems.Count > 0;
                NoSystemsAvailable = Systems.Count == 0;
            }
            catch (Exception ex) {
                ErrorMessage = $"Couldn't load systems: {ex.Message}";
                HasSystems = false;
                NoSystemsAvailable = true;
            }
            finally {
                IsLoading = false;
            }
        }

        // ---- Commands ----

        private bool CanSubmit() =>
            !IsBusy
            && SelectedSystem is not null
            && !string.IsNullOrWhiteSpace(SelectedRole)
            && !string.IsNullOrWhiteSpace(Justification);

        [RelayCommand(CanExecute = nameof(CanSubmit))]
        private async Task SubmitAsync() {
            var user = _currentUser.Current;
            if (user is null || SelectedSystem is null || string.IsNullOrWhiteSpace(SelectedRole)) return;

            IsBusy = true;
            ErrorMessage = null;
            try {
                var req = new AccessRequest {
                    RequesterUid = user.Uid,
                    RequesterDisplayName = string.IsNullOrWhiteSpace(user.DisplayName) ? user.Email : user.DisplayName,
                    RequesterEmail = user.Email,
                    BusinessSystemId = SelectedSystem.Id,
                    BusinessSystemName = SelectedSystem.Name,
                    AccessRoleRequested = SelectedRole!.Trim(),
                    Justification = Justification.Trim(),
                    Status = RequestStatus.Submitted
                };

                await _requests.CreateAsync(req);

                // Reset the form
                SelectedSystem = null;
                SelectedRole = null;
                Justification = string.Empty;

                if (Shell.Current is not null) {
                    await Shell.Current.DisplayAlert("Request submitted",
                        "Your access request has been submitted for approval.",
                        "OK");
                    await Shell.Current.GoToAsync("..");
                }
            }
            catch (Exception ex) {
                ErrorMessage = $"Couldn't submit: {ex.Message}";
            }
            finally {
                IsBusy = false;
            }
        }

        [RelayCommand]
        private async Task CancelAsync() {
            if (Shell.Current is not null) {
                await Shell.Current.GoToAsync("..");
            }
        }
    }
}
